const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const store = {};
const sandbox = { window: { NV: {} }, console, localStorage: {
  getItem: k => store[k] || null, setItem: (k, v) => { store[k] = v; }, removeItem: k => { delete store[k]; },
} };
for (const f of ['data/gameData', 'data/balance', 'data/consumables', 'engine/expedition']) vm.runInNewContext(fs.readFileSync('js/' + f + '.js', 'utf8'), sandbox);
const NV = sandbox.window.NV, E = NV.expedition;
const run = E.create('expedition', 0);
assert.deepStrictEqual(Array.from({ length: 10 }, (_, i) => E.bossIndex(run, (i + 1) * 2)), [0,1,2,3,4,5,6,7,8,9]);
for (let w = 1; w <= 20; w++) assert.equal(E.isBossWave(run, w), w % 2 === 0, 'Historia alterna asalto/jefe');
const legacy = { ...run, bossProgression: 'legacy' };
assert.deepStrictEqual([5, 10, 15, 20].map(w => E.bossIndex(legacy, w)), [0, 8, 4, 9]);
assert.equal(new Set(Array.from({ length: 10 }, (_, i) => E.bossIndex(run, (i + 1) * 2))).size, 10, 'una sola Historia cubre todo el roster');
assert.equal(E.bossIndex(E.create('endless', 0), 45), 8);
assert(!E.isBossWave(E.create('endless', 0), 2));
assert(E.isBossWave(E.create('endless', 0), 5));
E.beginWave(run); run.contract = true;
for (let i = 0; i < 3; i++) for (const weaponId of ['pistol', 'rifle']) E.kill(run, { kind: 'weapon', weaponId });
const reward = E.finishWave(run, 2, false);
assert.equal(reward, 52); assert.equal(run.contracts, 1); assert.equal(E.finishWave(run, 2, false), 0);
assert.equal(run.kills, 6); assert.equal(run.weaponKills.rifle, 3);
E.beginWave(run); run.contract = true; run.waveHits = 3;
E.finishWave(run, 5, true); assert.equal(run.contracts, 1, 'contrato de jefe falla con 3 golpes');
const levels = { rifle: 51, pistol: 1 }, kills = { rifle: 300, pistol: 0 };
const inv = ['rifle', 'pistol'].map(NV.weaponById);
assert.equal(E.syncArsenal(inv, levels, kills), 31); assert.equal(levels.pistol, 31); assert.equal(levels.rifle, 51);
const st = { run, wave: 5, player: { hp: 20, maxHp: 100 }, shards: 200, inventory: inv, levels, kills };
assert(E.prepare('training', st).ok); assert.equal(levels.pistol, 41); assert(!E.prepare('repair', st).ok, 'una preparación por parada');
run.prep = null; st.shards = 0; assert(!E.prepare('repair', st).ok); assert.equal(st.player.hp, 20);
st.shards = 200; assert(E.prepare('repair', st).ok); assert.equal(st.player.hp, 60);
const raw = { version: 1, character: 'boti', wave: 5, run, player: st.player, inventory: ['pistol', 'rifle'], currentWeapon: 'rifle',
  levels, kills, fus: { rifle: 2 }, consumables: [{ type: 'potion' }], shopBought: { hp: 2 }, upgradeSlots: [{ icon: 'hp', name: '+25 HP' }, { icon: 'hp', name: '+25 HP' }], score: 100, shards: 60, difficulty: 'hard' };
assert(E.save(raw)); const saved = E.load(); assert.equal(saved.fus.rifle, 2); assert.equal(saved.consumables[0].name, 'Poción'); assert.equal(saved.upgradeSlots.length, 2);
assert.equal(saved.difficulty, 'hard'); assert.equal(saved.currentWeapon, 'rifle');
assert.equal(saved.run.bossProgression, 'full-roster', 'el checkpoint conserva la progresión nueva');
const oldRun = { ...run }; delete oldRun.bossProgression;
const oldSaved = E.checkpoint({ ...raw, run: oldRun });
assert.equal(oldSaved.run.bossProgression, 'legacy');
assert(E.isBossWave(oldSaved.run, 5)); assert(!E.isBossWave(oldSaved.run, 2));
assert.equal(E.bossIndex(oldSaved.run, 10), 8, 'un guardado antiguo no cambia su siguiente jefe');
assert.equal(E.checkpoint({ ...raw, version: 2 }), null); assert.equal(E.checkpoint({ ...raw, character: 'invalid' }), null);
assert.equal(E.checkpoint({ ...raw, inventory: [] }), null); assert.equal(E.checkpoint({ ...raw, wave: NaN }), null);
const bad = E.checkpoint({ ...raw, player: { hp: -20, maxHp: NaN }, levels: { rifle: Infinity }, shards: -40, fus: { rifle: 100 } });
assert.equal(bad.player.hp, 1); assert.equal(bad.shards, 0); assert.equal(bad.fus.rifle, 3); assert.equal(bad.levels.rifle, 1);
assert.equal(NV.normalizePermUpgrades({ hp: -50, damage: Infinity }).hp, 0);
assert.equal(NV.normalizePermUpgrades({ hp: -50, damage: Infinity }).damage, 0);
E.complete(run, 20, 1000, true); E.complete(run, 20, 1000, true); assert.equal(E.profile().runs, 1); assert.equal(E.profile().wins, 1);
store.deadSingularityMeta = JSON.stringify({ metaShards: 177, permUpgrades: { hp: 3, damage: 2 } });
const backup = E.exportProgress();
assert.equal(backup.meta.metaShards, 177); assert.equal(backup.meta.permUpgrades.hp, 3);
store.deadSingularityMeta = '{}'; assert(E.importProgress(backup)); assert.equal(JSON.parse(store.deadSingularityMeta).metaShards, 177);
const previous = JSON.stringify(store);
assert.equal(E.importProgress({ ...backup, checkpoint: { version: 2 } }), false); assert.equal(JSON.stringify(store), previous);
assert.equal(E.importProgress({ ...backup, version: 2 }), false); assert.equal(JSON.stringify(store), previous);
E.clear(); assert.equal(E.load(), null); store.deadSingularityExpeditionV1 = 'broken'; assert.equal(E.load(), null);
console.log('RESULT expedition: checkpoints, progreso, contratos, economía, rutas y perfil OK');
