'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/ui/lobbyAtmosphere.js','utf8');
const callbacks={}; let hidden=false,rafId=0,draws=0;
const pending=new Map(),classes=new Set();
const wakes=new Map();let wakeId=0;
const context={clearRect(){},setTransform(){},fillRect(){draws++;},drawImage(){draws++;},beginPath(){},moveTo(){},lineTo(){},stroke(){},createRadialGradient(){return {addColorStop(){}};}};
const canvas={clientWidth:1280,clientHeight:800,parentElement:{},getContext(){return context;}};
const lobby={classList:{contains(name){return classes.has(name);}},getClientRects(){return classes.has('hidden')?[]:[{}];},addEventListener(){}};
const settings={graphics:{quality:'high',particles:true},gameplay:{reducedEffects:false},balance:{sentinel:17}};
const motion={matches:false,addEventListener(_name,fn){callbacks.motion=fn;}};
function ResizeObserver(fn){callbacks.resize=fn;this.observe=function(){};}
const document={get hidden(){return hidden;},getElementById(id){return id==='startScreen'?lobby:canvas;},createElement(){return {getContext(){return context;}};},addEventListener(name,fn){callbacks[name]=fn;}};
const window={NV:{settings,onSettingsChange(fn){callbacks.settings=fn;}},devicePixelRatio:3,ResizeObserver,matchMedia(){return motion;},addEventListener(name,fn){callbacks[name]=fn;},requestAnimationFrame(fn){pending.set(++rafId,fn);return rafId;},cancelAnimationFrame(id){pending.delete(id);}};
window.setTimeout=fn=>{wakes.set(++wakeId,fn);return wakeId;};window.clearTimeout=id=>wakes.delete(id);
const safeMath=Object.create(Math);safeMath.random=()=>{throw Error('No consumir RNG de combate');};
vm.runInNewContext(source,{window,document,ResizeObserver,MutationObserver:function(fn){callbacks.mutation=fn;this.observe=function(){};},performance:{now(){return 999999;}},Math:safeMath});
const snap=()=>window.NV.lobbyAtmosphere.getSnapshot();
assert(snap().active&&snap().stars<=1000&&snap().dpr===1.5);
assert.equal(pending.size,1);
const initial=snap().frames;
function advance(now){const [id,fn]=pending.entries().next().value;pending.delete(id);fn(now);}
advance(0);
const depthBefore=snap().probe.depth,distanceBefore=snap().probe.distance;
const [id,frame]=pending.entries().next().value;pending.delete(id);frame(40);
assert(snap().frames>initial&&draws>0);assert.equal(pending.size,1);
assert.equal(snap().motion,'forward');
assert(snap().probe.depth<depthBefore&&snap().probe.distance>distanceBefore,'Perspective must advance towards camera');
const beforeStorm=snap().time;
for(let now=80;now<=400;now+=40){callbacks.resize();callbacks.mutation();advance(now);}
assert(snap().time>beforeStorm+.25,'Repeated observer events cannot starve animation');
assert.equal(pending.size,1,'One animation loop after observer storm');
classes.add('hidden');callbacks.mutation();assert(!snap().active);assert.equal(pending.size,0);
classes.delete('hidden');callbacks.mutation();assert(snap().active);
hidden=true;callbacks.visibilitychange();assert(!snap().active);assert.equal(pending.size,0);
hidden=false;callbacks.visibilitychange();assert(snap().active);
motion.matches=true;callbacks.motion();assert(snap().reducedMotion&&!snap().active);assert.equal(snap().stopReason,'system-reduced-motion');assert.equal(pending.size,0);
motion.matches=false;const [wakeKey,wakeFn]=wakes.entries().next().value;wakes.delete(wakeKey);wakeFn();assert(snap().active,'Recover when media matches changes without an event');
motion.matches=false;settings.graphics.particles=false;callbacks.settings();assert(!snap().active);assert.equal(snap().stopReason,'particles-disabled');
settings.graphics.particles=true;settings.graphics.quality='performance';callbacks.settings();assert(snap().active&&snap().stars<=420);
callbacks.pagehide();assert(!snap().active);callbacks.pageshow();assert(snap().active);
callbacks.pagehide();window.NV.capabilities={isMobile:true};
vm.runInNewContext(source,{window,document,ResizeObserver,MutationObserver:function(fn){callbacks.mutation=fn;this.observe=function(){};},performance:{now(){return 0;}},Math:safeMath});
assert.equal(snap().travelSpeed,.18);assert(snap().active);
const mobileDistance=snap().probe.distance;
advance(0);
const [mobileId,mobileFrame]=pending.entries().next().value;pending.delete(mobileId);mobileFrame(60);
assert(snap().probe.distance-mobileDistance>0,'avance móvil medible sin RNG compartido');
window.NV.capabilities.orientation='portrait';callbacks.orientationchange();assert(!snap().active);
window.NV.capabilities.orientation='landscape';callbacks.orientationchange();assert(snap().active);
callbacks.pagehide();callbacks.pageshow();advance(5000);advance(5060);assert(snap().active&&snap().time>0);
settings.gameplay.reducedEffects=true;callbacks.settings();assert.equal(snap().stopReason,'reduced-effects');assert(!snap().active);
assert.equal(settings.balance.sentinel,17);
const html=fs.readFileSync('index.html','utf8');assert.equal((html.match(/id="lobbyCosmos"/g)||[]).length,1);
assert(html.includes('js/ui/lobbyAtmosphere.js')&&html.includes('css/lobby-cosmos.css'));
console.log('PASS lobby cosmos: animation, bounds, pause, preferences, isolated RNG and no simulation changes.');
