'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('js/ui/lobbyViewport.js','utf8'),values={},events={};
const lobby={style:{setProperty(k,v){values[k]=v;}}};
const visualViewport={width:800,height:320,offsetLeft:0,offsetTop:12,addEventListener(k,fn){events['visual:'+k]=fn;}};
const window={NV:{capabilities:{isMobile:true}},innerWidth:980,innerHeight:573,visualViewport,addEventListener(k,fn){events[k]=fn;}};
const document={getElementById(){return lobby;},addEventListener(k,fn){events[k]=fn;}};
vm.runInNewContext(source,{window,document});
assert.equal(values['--nv-lobby-height'],'320px');assert.equal(values['--nv-lobby-width'],'800px');
assert.equal(values['--nv-lobby-top'],'12px');
visualViewport.height=360;events['visual:resize']();assert.equal(values['--nv-lobby-height'],'360px');
window.visualViewport=null;events.pageshow();assert.equal(values['--nv-lobby-height'],'573px');
const css=fs.readFileSync('css/lobby-cosmos.css','utf8');
assert(css.includes('text-size-adjust:100%')&&css.includes('minmax(0,1fr)'));
assert(css.includes('#startScreen #heroName { font-size:clamp(20px,3vw,26px)'));
assert(css.includes('.main-lobby-actions { flex:0 0 auto; }'));
window.NV.capabilities.isMobile=false;values['--nv-lobby-width']='unchanged';
vm.runInNewContext(source,{window,document});assert.equal(values['--nv-lobby-width'],'unchanged');
console.log('PASS lobby visual viewport: browser chrome, offsets, resize, restoration, fallback and desktop isolation.');
