const fs=require('fs'),vm=require('vm'); let pass=0,fail=0; function t(n,f){try{f();pass++;console.log('  ok  '+n)}catch(e){fail++;console.log('  FAIL '+n+' -> '+e.message)}}
function mkCtx(){ const calls={strokes:0,arcs:0,fills:0,gradients:0,points:[]};
  const base={ save(){},restore(){},beginPath(){},stroke(){calls.strokes++},fill(){calls.fills++},
    arc(){calls.arcs++},moveTo(){},lineTo(x,y){calls.points.push([x,y])},closePath(){},setLineDash(){},
    createRadialGradient(){calls.gradients++;return{addColorStop(){}}},createLinearGradient(){calls.gradients++;return{addColorStop(){}}}};
  return { ctx:new Proxy(base,{get(tt,k){ if(k in calls)return calls[k]; if(k in tt)return tt[k]; return (tt[k]=function(){return tt}); },set(){return true}}), calls };
}
const NV={}; vm.runInNewContext(fs.readFileSync('js/render/metaReadability.js','utf8'),{window:{NV},Map,WeakMap,Math});
t('campo distingue masa comprimida de enemigos aislados',()=>{const dense=Array.from({length:8},(_,i)=>({x:100+i,y:100,radius:10})); const lone={x:500,y:400,radius:10}; const f=NV.buildDensityField(dense.concat(lone)); if(!(f.info.get(dense[0]).intensity>f.info.get(lone).intensity))throw Error('sin contraste');});
t('spatial grid evita comparación cuadrática en 80 dispersos',()=>{const es=Array.from({length:80},(_,i)=>({x:(i%10)*200,y:Math.floor(i/10)*200,radius:10})); const f=NV.buildDensityField(es); if(f.comparisons>300)throw Error('comparaciones='+f.comparisons);});
t('cálculo no muta objetos de gameplay',()=>{const e={x:1,y:2,radius:10};const before=JSON.stringify(e);NV.buildDensityField([e]);if(JSON.stringify(e)!==before)throw Error('mutó');});
t('neblina: gradiente radial solo en núcleos densos, con tope',()=>{const {ctx,calls}=mkCtx(); const dense=Array.from({length:8},(_,i)=>({x:100+i,y:100,radius:10})); const info=NV.buildDensityField(dense).info; if(!NV.drawDensityFog(ctx,dense,info,{t:1}))throw Error('sin neblina'); if(calls.gradients<1)throw Error('sin gradiente'); const far=[{x:600,y:400,radius:10}]; if(NV.drawDensityFog(ctx,far,info,{t:1}))throw Error('aislado dibujó'); const many=Array.from({length:80},(_,i)=>({x:100+(i%8)*4,y:100+Math.floor(i/8)*4,radius:12})); const info2=NV.buildDensityField(many).info; const m=mkCtx(); NV.drawDensityFog(m.ctx,many,info2,{t:1}); if(m.calls.gradients>10)throw Error('cap superado: '+m.calls.gradients);});
t('contacto se muestra solo cerca/ataque o completo en debug',()=>{const {ctx}=mkCtx(),p={x:0,y:0}; if(NV.drawContactReadability(ctx,{x:200,y:0,radius:10},p,false,{t:1}))throw Error('lejano visible'); if(!NV.drawContactReadability(ctx,{x:35,y:0,radius:10},p,false,{t:1}))throw Error('cercano oculto'); if(!NV.drawContactReadability(ctx,{x:200,y:0,radius:10},p,true,{t:1}))throw Error('debug oculto');});
t('feedback de daño conserva anillo y disco local',()=>{const {ctx,calls}=mkCtx(),p={x:10,y:10};if(!NV.drawDamageFeedback(ctx,p,{life:.4,critical:false,flash:.05},{t:1}))throw Error('sin impacto');if(calls.strokes!==1||calls.fills!==1||calls.arcs!==2)throw Error('anillo o disco perdido');});
t('visuales meta obsoletos del jugador no tienen renderer ni estado',()=>{const g=fs.readFileSync('js/game.js','utf8');for(const symbol of ['drawInvulnerabilityFeedback','drawMomentumReadability','invulnerabilityFeedback','previousInvulnerability','momentumVisual']){if(symbol in NV||g.includes(symbol))throw Error('persistió '+symbol);}for(const key of ['invulnerability','momentum'])if(key in NV.META_VIS_OPTIONS)throw Error('toggle obsoleto '+key);});
t('target autofire usa rombo rotante y círculo de búsqueda',()=>{const {ctx,calls}=mkCtx();if(NV.drawAutofireTarget(ctx,null,0,{x:0,y:0},false,false,{t:1}))throw Error('no debió dibujar target');if(!NV.drawAutofireTarget(ctx,{x:10,y:10,radius:8},0,{x:0,y:0},true,false,{t:1}))throw Error('sin rombo');if(calls.strokes<1)throw Error('sin trazos');});
t('intención suprime marca erratic; conserva ranged y omite Shielder',()=>{const p={x:100,y:0};const erratic=mkCtx();if(NV.drawEnemyIntent(erratic.ctx,{x:0,y:0,radius:10,behavior:'erratic',erraticTimer:.1,angle:0},p,{t:1}))throw Error('erratic aún reporta indicador');if(erratic.calls.strokes!==0)throw Error('trazo erratic persiste');const ranged=mkCtx();if(!NV.drawEnemyIntent(ranged.ctx,{x:0,y:0,radius:10,behavior:'ranged'},p,{t:1})||ranged.calls.strokes===0)throw Error('ranged perdido');const shield=mkCtx();if(NV.drawEnemyIntent(shield.ctx,{x:0,y:0,radius:10,behavior:'shield',shield:true,shieldCd:0},p,{t:1}))throw Error('shield aún reporta indicador');if(shield.calls.arcs!==0||shield.calls.strokes!==0)throw Error('arco Shielder persiste');});
t('paleta, opciones y toggles por efecto existen',()=>{if(!NV.META_VIS_PALETTE.danger)throw Error('paleta');for(const k of ['density','contact','damage','autofire','intent','legend'])if(!(k in NV.META_VIS_OPTIONS))throw Error('falta opción '+k);if(!NV.setMetaVisOption('density',false)||NV.META_VIS_OPTIONS.density)throw Error('toggle falla');NV.setMetaVisOption('density',true);});
t('game.js dibuja neblina en capa previa bajo entidades',()=>{const g=fs.readFileSync('js/game.js','utf8');const fog=g.indexOf('NV.drawDensityFog');const enemies=g.indexOf('if (!(e.atkFlash > 0)) drawEnemy(e);');if(!(fog>=0&&fog<enemies))throw Error('orden de capas incorrecto');});
console.log('RESULT meta_density: pass='+pass+' fail='+fail);process.exit(fail?1:0);